### PR TITLE
Add YDKJS. It's a really good series.

### PR DESCRIPTION
**Pull request by jhare**
@getify is a serious authority on Javascript and I think that after having introduction to all of the functional/OO concepts in Javascript covering it deeply is a good idea.

Are you all familiar with Kyle Simpson's work?

### CODE REVIEW

**Comment by jhare** [comment]
https://github.com/getify/You-Dont-Know-JS/blob/master/README.md#you-dont-know-js-book-series

**Comment by jhare** [comment]
I marked it as free because you can read it on Github in full, but it is available through O'Reily as well.

As an aside, I have no commercial affiliation with Kyle Simpson.

**Comment by radosavljevic** [comment]
:+1:

**Comment by nilssolanki** [comment]
Definitely a worthwhile addition.

**Comment by GatoBlabla** [comment]
I agree too, YDKJS is a brillant serie, as well as "Secret of the JavaScript Ninja" which isn't free but worth it !

**Comment by lukefrake** [comment]
:+1: x 100!

**Comment by ericdouglas** [comment]
@jhare it is indeed a great series of books, but all the topics that he covers are covered by other books here.

I know, there are **several** excellent books outside this list, but the point here is to be as concise as possible.

Maybe we can create a system to suggest complementary books. :bulb: 

What I think is: 

- open an issue with the name of the book
- put a label representing which section that the book fits
- who that want to recommend the same book should comment in this issue describing why he/she thinks that it's valid invest time to read this book. **OBS**: should be at least a **short commentary**, not just a :+1: 

What you guys think about it?

@GatoBlabla "Secret of the JavaScript Ninja" is a great book too, but they're doing a second version of this book.

**Comment by raganwald** [comment]
I'm a big fan of YDKJS, but don't agree that it should be placed under `Advanced JavaScript`. That term is a little broad, and might be mistaken to imply that none of the other books are advanced. My suggestion is `JavaScript Semantics`, which really captures what the book series is actually about: Understanding how the language actually behaves.

**Comment by jhare** [comment]
I struggled with finding the right term and agree with your "semantics" one
much more.

**Comment by jhare** [comment]
I'll take some time this evening to craft an issue the way @ericdouglas specified and we can go from there. Thanks!

**Comment by YulongW** [comment]
Agreed 100%.

**Comment by ikeagold** [comment]
@jhare :+1: :100:

**Comment by josescasanova** [comment]
+1

**Comment by ericdouglas** [comment]
@jhare now we have an [Additional resources](https://github.com/javascript-society/javascript-path#additional-resources) section, and the "You Don't Know JS" series was included. :smile:

**Pull request closed without merging**
